swarm:
    image: dockerswarm/swarm
    restart: always
    command: manage --strategy={{ docker_swarm_strategy }} --tlsverify --tlscacert={{ docker_tls_path }}/ca.pem --tlscert={{ docker_tls_path }}/cert.pem --tlskey={{ docker_tls_path }}/key.pem file:///root/.swarm/cluster
    volumes:
      - /root/.swarm:/root/.swarm
      - "{{ docker_tls_path }}:{{ docker_tls_path }}"
    ports:
      - "127.0.0.1:2375:2375"

jpydb:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: jupyterhub
      POSTGRES_PASSWORD: "{{ jpy_postgres_password }}"
      PGDATA: /var/lib/postgresql/data/jupyterhub
    volumes:
      - /srv/postgres/jupyterhub:/var/lib/postgresql/data/jupyterhub

jupyterhub:
    image: triggers/jupyterhub
    restart: always
    environment:
      OAUTH_CLIENT_ID: "{{ oauth_client_id }}"
      OAUTH_CLIENT_SECRET: "{{ oauth_client_secret }}"
      OAUTH_CALLBACK_URL: "{{ oauth_callback_url }}"
      HOSTED_DOMAIN: "{{ oauth_hosted_domain }}"
      JPY_COOKIE_SECRET: "{{ cookie_secret }}"
      JPY_DB_USER: postgres
      JPY_DB_PASSWORD: "{{ jpy_postgres_password }}"
      JPY_DB_NAME: jupyterhub
      CONFIGPROXY_AUTH_TOKEN: "{{ configproxy_auth_token }}"
      DOCKER_TLS_CERT: "{{ docker_tls_path }}/cert.pem"
      DOCKER_TLS_KEY: "{{ docker_tls_path }}/key.pem"
      HUB_IP: "{{ servicenet_ip }}"
      NBGRADER_EXCHANGE: "{{ exchange }}"
    volumes:
      - /srv/jupyterhub_users:/srv/jupyterhub_users
      - "{{ docker_tls_path }}:{{ docker_tls_path }}"
      - /var/run/restuser.sock:/restuser.sock
    ports:
      - "{{ servicenet_ip }}:8000:8000"
      - "{{ servicenet_ip }}:8081:8081"
    links:
      - swarm
      - jpydb:postgres
