---
- fail: msg="nfsserver is not defined"
  when: nfsserver == ''
- fail: msg="nfsdomain is not defined"
  when: nfsdomain == ''
- fail: msg="exchange is not defined"
  when: exchange == ''

- name: install nfs client
  yum: name=nfs-utils state=present

- name: unmount exchange nsf dir
  shell: umount {{ exchange }} || true

- name: unmount jupyter nsf dir
  shell: umount /jupyter || true

- name: mount exchange nfs dir
  mount: path={{ exchange }} src={{ hostvars[nfsserver]['servicenet_ip'] }}:/exchange fstype=nfs opts={{ nfsoptions }} state=mounted

- name: mount jupyter nfs dir
  mount: path=/jupyter src={{ hostvars[nfsserver]['servicenet_ip'] }}:/jupyter fstype=nfs opts={{ nfsoptions }} state=mounted
